version: '3.7'
services:

  app:
    container_name: ktamaral-portfolio-react
    build:
      context: .
      dockerfile: Dockerfile
    #command: 'tail -f /dev/null'
    volumes:
      - './:/home/ktamaral'
      - '/home/ktamaral/node_modules'
    #env_file: .env
    ports:
      - "3000:3000"
